// site/presentation/src/templates/fragments/base-head-fragment/base-head-fragment.component.tsx
export const BaseHeadFragment = () => {
  return (
    <>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <meta name="theme-color" content="#e0e0e0" />
      <title>owwo</title>

      <link rel="stylesheet" href="/public/styles/index.css" />
    </>
  );
};

// src/svelte/fragments/base-head.fragment.svelte
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<meta name="theme-color" content="#e0e0e0" />
<title>OWWO</title>

<link rel="stylesheet" href="/public/styles/reset.css" />
<link rel="stylesheet" href="/public/styles/scrollbar.css" />
<link rel="stylesheet" href="/public/styles/hr.css" />
<link rel="stylesheet" href="/public/styles/border.css" />
<link rel="stylesheet" href="/public/styles/font.css" />

<link rel="stylesheet" href="/public/styles/layout.css" />

<link rel="stylesheet" href="/public/styles/constants/color.constants.css" />
