// adapters/svelte-adapter/src/templates/pages/about-page/about-page.svelte
<script lang="ts">
  import type { AboutPageProps } from "./about-page.svelte";
  import { BaseLayout } from "../../layouts";
  import { Text } from "../../components";

  export let props: AboutPageProps;
  const { text = "" } = props;
</script>

<BaseLayout>
  <div class="grid">
    <Text {text} className="grid__right-content" />
  </div>
</BaseLayout>

// site/site-ui/pages/about-page/src/about-page.component.tsx
import { BaseLayout } from "@site-ui/base-layout";

import { Text } from "@ui/text";

import type { AboutPageType } from "./about-page.interface";

const AboutPage: AboutPageType = (props) => {
  const { text = "" } = props;

  // TODO type
  return (
    <BaseLayout>
      <div class="grid">
        <Text text={text} className="grid__right-content" />
      </div>
    </BaseLayout>
  );
};

export { AboutPage };
