// adapters/svelte-adapter/src/templates/pages/about-page/about-page.svelte
<script lang="ts">
  import type { AboutPageProps } from "./about-page.svelte";
  import { BaseLayout } from "../../layouts";
  import { Text } from "../../components";

  export let props: AboutPageProps;
  const { text = "" } = props;
</script>

<BaseLayout>
  <div class="grid">
    <Text {text} className="grid__right-content" />
  </div>
</BaseLayout>

// src/presentation/src/templates/pages.bak/about-page/about-page.component.tsx
import { Text } from "../../components";
import { BaseLayout } from "../../layouts";
import type { AboutPageType } from "./about-page.interface";

const AboutPage: AboutPageType = (props) => {
  const { aboutPageContent } = props;

  return (
    <BaseLayout>
      <div class="grid">
        <Text text={aboutPageContent} className="grid__right-content" />
      </div>
    </BaseLayout>
  );
};

export { AboutPage };
