// ui/node-link/src/node-link__image/node-link-image.component.tsx
import type { NodeLinkImageType } from "./node-link-image.interface";

const NodeLinkImage: NodeLinkImageType = (props) => {
  const { variant = "small", image } = props;

  if (variant === "big") {
    const imageSrcset = `${image.h32}, ${image.h32_2x} 2x`;
    // TODO change mock data
    // TODO provede 2x image logic to picture
    const image2xSrcset = `https://images.placeholders.dev/?width=64&height=64`;

    return (
      <picture>
        <source srcset={imageSrcset} />
        <source srcset={image2xSrcset} />
        <img
          src="https://images.placeholders.dev/?width=64&height=64"
          alt="node-info__image"
        />
      </picture>
    );
  }

  const imageSrcset = `${image.h16}, ${image.h16_2x} 2x`;
  // TODO change mock data
  // TODO provede 2x image logic to picture
  const image2xSrcset = `https://images.placeholders.dev/?width=64&height=64`;

  return (
    <picture>
      <source srcset={imageSrcset} />
      <source srcset={image2xSrcset} />
      <img
        src="https://images.placeholders.dev/?width=64&height=64"
        alt="node-info__image"
      />
    </picture>
  );
};

export { NodeLinkImage };

// site/_svelte-templates/src/components/node-link__image.component.svelte
<script>
  export let image;
  export let variant = "small";
</script>

{#if variant === "small"}
  <picture>
    <source srcset="{image.h16}, {image.h16_2x} 2x" />
    <source srcset="https://images.placeholders.dev/?width=64&height=64" />
    <img
      src="https://images.placeholders.dev/?width=64&height=64"
      alt="node-info__image"
    />
  </picture>
{:else if variant == "big"}
  <picture>
    <source srcset="{image.h32}, {image.h32_2x} 2x" />
    <source srcset="https://images.placeholders.dev/?width=64&height=64" />
    <img
      src="https://images.placeholders.dev/?width=64&height=64"
      alt="node-info__image"
    />
  </picture>
{/if}
