// site/site-ui/pages/node-extended-page/src/node-extended-page.component.tsx
// TODO unused component
import { NodeExtendedLayout } from "@site-ui/extended-layout";
import { HeaderFragment } from "@site-ui/header-fragment";
import { NodeExtendedFragment } from "@site-ui/node-extended-fragment";

import { FullGridWrapContainer } from "@ui/full-grid-wrap-container";
import { Hr } from "@ui/hr";
import { Logo } from "@ui/logo";
import { NodeCard } from "@ui/node-card";
import { NodeInfo } from "@ui/node-info";
import { NodeNavigation } from "@ui/node-navigation";
import { NodeTitle } from "@ui/node-title";
import { Text } from "@ui/text";

import type { NodeExtendedPageType } from "./node-extended-page.interface";

// TODO much comments - for what?
const NodeExtendedPage: NodeExtendedPageType = (props) => {
  const { node } = props;

  const { title } = node;
  const { content } = node;

  const siblingsArray = node.meta.siblings;
  const siblingsLength = siblingsArray.length;
  const currentSiblingId = node.meta.id;
  const currentSiblingIndex = siblingsArray.findIndex((sibling, index) => {
    if (sibling.meta.id === currentSiblingId) return index;
    else return 0;
  });

  // TODO make it optional. only on js, client side
  const prevSibling = siblingsArray[currentSiblingIndex - 1];
  const nextSibling = siblingsArray[currentSiblingIndex + 1];

  // 	    <!-- <FullGridWrapContainer limit={32}> -->
  // <!--   <h2 class="random-elements__title"> -->
  // <!--     {node.meta.author} -->
  // <!--   </h2> -->
  // <!--   {#each node.randomUserElements as randomElement} -->
  // <!--     <NodeInfo node={randomElement} type="cover" /> -->
  // <!--   {/each} -->
  // <!-- </FullGridWrapContainer> -->
  //
  // <!-- <FullGridWrapContainer> -->
  // <!--   <Logo className="random-elements__title random-elements__logo" /> -->
  // <!--   {#each node.randomOwwoElements as randomElement} -->
  // <!--     <NodeInfo node={randomElement} type="cover" /> -->
  // <!--   {/each} -->
  // <!-- </FullGridWrapContainer> -->

  return (
    <>
      <NodeExtendedLayout>
        <div class="grid todo" style="color: red;">
          <ul>
            <li>elements отображаются оригинальном формате</li>
            <li>
              возможность добавить скрипт из стандартной библиотеки, который
              меняет верстку на extended
            </li>
          </ul>
        </div>

        <NodeExtendedFragment content={content} />

        {(prevSibling || nextSibling) && (
          <NodeNavigation
            current={currentSiblingIndex}
            length={siblingsLength}
            prevNode={prevSibling}
            nextNode={nextSibling}
          />
        )}

        <div class="wrapper node-extended__layout">
          <span class="grid element-info__data-wrapper">
            <NodeInfo node={node} title={false} description={false} />
            <div class="grid__right-content">
              <NodeTitle title={node.title} />
              <Text text={node.description} className="grid__right-content" />
            </div>
          </span>

          <HeaderFragment bottom />
        </div>
      </NodeExtendedLayout>
    </>
  );
};

export { NodeExtendedPage };

// adapters/svelte-adapter/src/templates/pages/node-extended-page/node-extended-page.svelte
<script lang="ts">
  import type { NodeExtendedPageProps } from "./node-extended-page.svelte";
  import { NodeExtendedLayout } from "../../layouts";
  import { Hr } from "../../components";
  import { NodeCard } from "../../components";

  import { FullGridWrapContainer } from "../../components";
  import { Logo } from "../../components";
  import { HeaderFragment } from "../../fragments";

  import { NodeExtendedContentFragment } from "../../fragments";
  // TODO to fragments?
  import { NodeNavigation } from "../../components";

  import { Text } from "../../components";
  import { NodeTitle } from "../../components";
  import { NodeInfo } from "../../components";

  export let props: NodeExtendedPageProps;
  const { node } = props;

  const { title } = node;
  const { content } = node;

  // TODO refactor
  const siblingsArray = node.meta.siblings;
  const siblingsLength = siblingsArray.length;
  const currentSiblingId = node.meta.id;
  const currentSiblingIndex = siblingsArray.findIndex((sibling, index) => {
    if (sibling.meta.id === currentSiblingId) return index;
    else return 0;
  });

  // TODO make it optional. only on js, client side
  const prevSibling = siblingsArray[currentSiblingIndex - 1];
  const nextSibling = siblingsArray[currentSiblingIndex + 1];
</script>

<NodeExtendedLayout>
  <div class="grid todo" style="color: red;">
    <ul>
      <li>elements отображаются оригинальном формате</li>
      <li>
        возможность добавить скрипт из стандартной библиотеки, который меняет
        верстку на extended
      </li>
    </ul>
  </div>

  <NodeExtendedContentFragment {content} />

  {#if prevSibling || nextSibling}
    <NodeNavigation
      current={currentSiblingIndex}
      length={siblingsLength}
      prevNode={prevSibling}
      nextNode={nextSibling}
    />
  {/if}

  <div class="wrapper node-extended__layout">
    <span class="grid element-info__data-wrapper">
      <NodeInfo {node} title={false} description={false} />
      <div class="grid__right-content">
        <NodeTitle title={node.title} />
        <Text text={node.description} className="grid__right-content" />
      </div>
    </span>

    <!-- <FullGridWrapContainer limit={32}> -->
    <!--   <h2 class="random-elements__title"> -->
    <!--     {node.meta.author} -->
    <!--   </h2> -->
    <!--   {#each node.randomUserElements as randomElement} -->
    <!--     <NodeInfo node={randomElement} type="cover" /> -->
    <!--   {/each} -->
    <!-- </FullGridWrapContainer> -->

    <!-- <FullGridWrapContainer> -->
    <!--   <Logo className="random-elements__title random-elements__logo" /> -->
    <!--   {#each node.randomOwwoElements as randomElement} -->
    <!--     <NodeInfo node={randomElement} type="cover" /> -->
    <!--   {/each} -->
    <!-- </FullGridWrapContainer> -->

    <HeaderFragment position="bottom" />
  </div>
</NodeExtendedLayout>

<style>
  :global(.random-elements__title) {
    mix-blend-mode: difference;
    pointer-events: none;
    position: absolute !important;
    top: var(--GRID-GAP-2);
    left: var(--GRID-GAP-4);
  }

  :global(.random-elements__logo path) {
    fill: var(--DARK) !important;
  }

  :global(.random-elements__title) {
    color: var(--DARK) !important;
  }
</style>
