// src/presentation/src/templates/components/image/image.component.tsx
import { ImageVariantName } from "../../globals";
import type { ImageProps } from "./image.interface";

export const Image: Component<ImageProps> = (props) => {
  const { image, id, variant } = props;

  const imageId = `image-${id}`;
  const imageSrcset = `${image[`${variant}_2x`]}`;
  const image2xSrcset = `${image[variant]}, ${image[`${variant}_2x`]} 2x`;

  const imageOriginalSource = image[ImageVariantName.Original];

  return (
    <picture>
      <source srcset={imageSrcset} media="(max-width: 360px)" />
      <source srcset={image2xSrcset} />
      <img id={imageId} src={imageOriginalSource} alt="page-cover" />
    </picture>
  );
};

// adapters/svelte-adapter/src/templates/components/image/image.svelte
<script lang="ts">
  import type { ImageProps } from "./image.svelte";

  export let props: ImageProps;

  const { image, id, variant } = props;
</script>

<picture>
  <!-- TODO 2x: -->
  <source srcset={image[`${variant}_2x`]} media="(max-width: 360px)" />
  <source srcset="{image[variant]}, {image[`${variant}_2x`]} 2x" />
  <img id="image-{id}" src={image.original} alt="page-cover" />
</picture>
